# Generated by Django 3.2.5 on 2021-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame_alt_anatomia',
            fields=[
                ('id_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('id_alteracao', models.IntegerField()),
            ],
        ),
    ]
