# Generated by Django 3.2.5 on 2021-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_tipo_den', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
