# Generated by Django 3.2.5 on 2021-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_tipo_den', '0003_teste_denticao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='sexo',
        ),
        migrations.AddField(
            model_name='teste',
            name='conf_mista',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='conf_permamente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='denticao_modelo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
