# Generated by Django 3.2.5 on 2021-09-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_tipo_den', '0004_auto_20210902_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='conf_permamente',
            new_name='conf_permanente',
        ),
    ]
