# Generated by Django 3.2.5 on 2021-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_sexo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='sexo',
            new_name='sexo_banco',
        ),
        migrations.AddField(
            model_name='teste',
            name='conf_fem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='conf_masc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='sexo_modelo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
