# Generated by Django 3.2.5 on 2021-07-28 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import panoramica.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panoramica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panoramica', models.ImageField(upload_to=panoramica.models.user_directory_path)),
                ('n_os', models.CharField(blank=True, max_length=10, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
